/* ===========================================================================
   004_create_indexes.sql  (PostgreSQL)

   GENERATED by scripts/translate_tsql_to_postgres.py from sql/004_create_indexes.sql.
   Do not edit by hand - edit the T-SQL source and re-run the translator, or
   the two dialects drift and only one of them is tested.

   Verified by .github/workflows/postgres.yml against a real PostgreSQL 16.
   =========================================================================== */

/* ===========================================================================
   004_create_indexes.sql
   Schema version: 1.0.0

   Indexing strategy
   -----------------
   The workload is analytical reads generated by an LLM, so the access paths
   are broad but predictable:

     * almost every query filters or joins on tenant_id  (isolation predicate)
     * customer-centric lookups dominate
     * date-range scans over invoices, usage and tickets drive the KPI views

   Leading every non-clustered index with tenant_id matches the tenant
   predicate the SQL guard injects, so the isolation filter is served by the
   index rather than by a post-scan filter.

   Included columns are chosen to make the analytics views in 005 covering
   where that is cheap. They are not exhaustive: 004 is a starting point to be
   revisited with real execution plans, not a claim of optimality.

   Idempotent: every index is guarded by an existence check.
   =========================================================================== */

/* --------------------------------------------------------------------------
   core.customers
   -------------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_customers_tenant_status')
CREATE INDEX IX_customers_tenant_status
    ON core.customers (tenant_id, status)
    INCLUDE (customer_code, display_name, segment, region, signup_date, churn_date);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_customers_churn_date')
CREATE INDEX IX_customers_churn_date
    ON core.customers (churn_date)
    WHERE churn_date IS NOT NULL;   -- filtered: only churned rows are ever scanned here

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_customers_display_name')
CREATE INDEX IX_customers_display_name
    ON core.customers (display_name)
    INCLUDE (customer_id, tenant_id, legal_name);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_contacts_customer')
CREATE INDEX IX_contacts_customer
    ON core.customer_contacts (customer_id) INCLUDE (full_name, email, is_primary);

/* --------------------------------------------------------------------------
   core.subscriptions - the spine of every revenue metric
   -------------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_subs_tenant_customer')
CREATE INDEX IX_subs_tenant_customer
    ON core.subscriptions (tenant_id, customer_id)
    INCLUDE (plan_id, status, started_on, ended_on, mrr_amount, seats, is_trial);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_subs_status_dates')
CREATE INDEX IX_subs_status_dates
    ON core.subscriptions (status, started_on, ended_on) INCLUDE (customer_id, mrr_amount);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_sub_changes_date_type')
CREATE INDEX IX_sub_changes_date_type
    ON core.subscription_changes (changed_on, change_type)
    INCLUDE (customer_id, tenant_id, mrr_delta);

/* --------------------------------------------------------------------------
   core.usage_daily - the largest table; date-range scans must be seekable
   -------------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_usage_date_customer')
CREATE INDEX IX_usage_date_customer
    ON core.usage_daily (usage_date, customer_id)
    INCLUDE (product_id, active_users, api_calls, storage_gb, sessions);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_usage_customer_date')
CREATE INDEX IX_usage_customer_date
    ON core.usage_daily (customer_id, usage_date) INCLUDE (active_users, api_calls);

/* --------------------------------------------------------------------------
   billing
   -------------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_invoices_tenant_customer')
CREATE INDEX IX_invoices_tenant_customer
    ON billing.invoices (tenant_id, customer_id)
    INCLUDE (issue_date, due_date, total_amount, amount_paid, status, paid_date);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_invoices_issue_date')
CREATE INDEX IX_invoices_issue_date
    ON billing.invoices (issue_date) INCLUDE (customer_id, total_amount, status, currency_code);

/* Overdue invoices are queried constantly by the risk views, and they are a
   small fraction of the table: a filtered index keeps that lookup tiny. */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_invoices_overdue')
CREATE INDEX IX_invoices_overdue
    ON billing.invoices (customer_id, due_date)
    INCLUDE (total_amount, amount_paid)
    WHERE status IN ('open', 'overdue', 'partial');

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_invoice_items_invoice')
CREATE INDEX IX_invoice_items_invoice
    ON billing.invoice_items (invoice_id) INCLUDE (product_id, plan_id, line_amount, quantity);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_payments_customer_date')
CREATE INDEX IX_payments_customer_date
    ON billing.payments (customer_id, payment_date) INCLUDE (amount, status, method, days_late);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_payments_invoice')
CREATE INDEX IX_payments_invoice ON billing.payments (invoice_id) INCLUDE (amount, status);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_refunds_customer_date')
CREATE INDEX IX_refunds_customer_date
    ON billing.refunds (customer_id, refund_date) INCLUDE (amount, reason_code, is_partial);

/* --------------------------------------------------------------------------
   support
   -------------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_tickets_tenant_customer')
CREATE INDEX IX_tickets_tenant_customer
    ON support.tickets (tenant_id, customer_id)
    INCLUDE (opened_at_utc, first_response_at_utc, resolved_at_utc, priority, status, product_id);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_tickets_opened')
CREATE INDEX IX_tickets_opened
    ON support.tickets (opened_at_utc) INCLUDE (customer_id, priority, status, satisfaction_score);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ticket_events_ticket')
CREATE INDEX IX_ticket_events_ticket
    ON support.ticket_events (ticket_id, event_at_utc) INCLUDE (event_type, actor_type);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_breaches_customer')
CREATE INDEX IX_breaches_customer
    ON support.sla_breaches (customer_id)
    INCLUDE (ticket_id, breach_type, breach_minutes, detected_at_utc, credit_issued);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_breaches_detected')
CREATE INDEX IX_breaches_detected
    ON support.sla_breaches (detected_at_utc) INCLUDE (customer_id, breach_type);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_sla_policies_lookup')
CREATE INDEX IX_sla_policies_lookup
    ON support.sla_policies (plan_tier, priority, effective_from)
    INCLUDE (first_response_minutes, resolution_minutes, version, effective_to, is_current);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_incidents_started')
CREATE INDEX IX_incidents_started
    ON support.incidents (started_at_utc) INCLUDE (incident_code, severity, product_id, affected_region);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_incident_impact_customer')
CREATE INDEX IX_incident_impact_customer
    ON support.incident_impact (customer_id) INCLUDE (incident_id, impact_level, downtime_minutes, credit_amount);

/* --------------------------------------------------------------------------
   analytics / ai
   -------------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_health_snapshot')
CREATE INDEX IX_health_snapshot
    ON analytics.customer_health (snapshot_date, risk_band)
    INCLUDE (customer_id, tenant_id, health_score, churn_risk_pct);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_glossary_current')
CREATE INDEX IX_glossary_current
    ON ai.business_glossary (is_current, term) INCLUDE (definition, sql_guidance, version);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_sql_examples_active')
CREATE INDEX IX_sql_examples_active
    ON ai.approved_sql_examples (is_active, category) INCLUDE (question, tables_used);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_audit_trace')
CREATE INDEX IX_audit_trace ON ai.audit_events (trace_id);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_audit_occurred')
CREATE INDEX IX_audit_occurred
    ON ai.audit_events (occurred_at_utc DESC) INCLUDE (route, sql_allowed, error_category);
DO $$ BEGIN RAISE NOTICE '004_create_indexes.sql complete.'; END $$;
