"""
Deterministic synthetic data for Northwind Cloud.

Everything here is driven by one seed (`COPILOT_SEED`, default 20240601), so
two runs on two machines produce byte-identical data. That matters because the
evaluation set asserts specific answers: "the June 2026 incident affected N
customers" is only a valid test if N is stable.

No real personal data is used. Names, emails and companies are generated by
Faker from the seeded generator.

The edge cases in `EDGE_CASES` are not decoration. Each one exists so that some
retrieval, SQL or evaluation behaviour can be tested against data that actually
contains the awkward shape.
"""

from __future__ import annotations

import logging
import random
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta

from ..config import Settings

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Data window and volumes
# ---------------------------------------------------------------------------
DATA_START = date(2023, 1, 1)
DATA_END = date(2026, 9, 30)

# Usage is the largest table by far. A full-history daily grain would be
# ~1.2M rows for no analytical gain at this scale, so usage is generated for a
# rolling window that still covers year-over-year comparisons.
USAGE_WINDOW_DAYS = 400


@dataclass(frozen=True)
class Volumes:
    """Row targets. `demo` shrinks everything so the notebook runs quickly."""

    customers: int = 600
    tickets: int = 4000
    incidents: int = 9
    health_snapshot_months: int = 12
    usage_window_days: int = USAGE_WINDOW_DAYS

    @classmethod
    def demo(cls) -> Volumes:
        return cls(customers=90, tickets=500, incidents=5,
                   health_snapshot_months=4, usage_window_days=90)


# ---------------------------------------------------------------------------
# Deliberate patterns. Documented here so the evaluation set can assert them.
# ---------------------------------------------------------------------------
EDGE_CASES = {
    "seasonal_revenue": "Q4 (Oct-Dec) new business runs ~40% above baseline; Q1 ~20% below.",
    "churn_spike": "Q2 2025 churn is ~2.5x baseline, caused by the SEV1 incident in June 2025.",
    "late_payments": "~18% of invoices are paid after the due date; ~6% are still unpaid.",
    "partial_refunds": "~40% of refunds are partial rather than full.",
    "duplicate_names": "8 near-duplicate customer name pairs (e.g. 'Acme Corp' / 'ACME Corporation').",
    "missing_values": "industry ~12% NULL, employee_count ~15% NULL, satisfaction_score ~55% NULL, phone ~30% NULL.",
    "plan_migrations": "~22% of subscriptions have at least one upgrade or downgrade.",
    "cancelled_subscriptions": "Cancelled subscriptions retain their history and MRR contribution up to the end date.",
    "reactivated_customers": "~4% of churned customers return with a new subscription and is_reactivated = 1.",
    "sla_breaches": "~11% of tickets breach first response; ~7% breach resolution.",
    "high_support_low_usage": "25 customers deliberately combine many tickets with near-zero usage (at-risk signal).",
    "incident_scope": "Incidents are scoped by product and/or region; some are platform-wide (product_id NULL).",
    "multi_currency": "EMEA tenant bills in EUR; NA and APAC in USD.",
    "timezone_edges": "~5% of tickets open between 23:00 and 23:59 UTC, so local-day and UTC-day differ.",
    "cross_tenant": "Customers are spread across 3 tenants so isolation can be tested.",
    "trial_customers": "~8% of customers are trial-only and must be excluded from MRR.",
}

INDUSTRIES = [
    "Financial Services", "Healthcare", "Retail", "Manufacturing", "Technology",
    "Logistics", "Education", "Energy", "Telecommunications", "Public Sector",
    "Media", "Professional Services",
]
TICKET_CATEGORIES = [
    "Billing", "Data Import", "Performance", "Access / SSO", "API Error",
    "Reporting", "Integration", "Feature Request", "Outage", "Configuration",
]
CANCEL_REASONS = [
    "Budget reduction", "Switched to competitor", "Product did not meet needs",
    "Company acquired", "Consolidating vendors", "Poor support experience",
    "Project completed", "Lack of adoption",
]
REFUND_REASONS = [
    ("service_credit", "Service credit for SLA breach"),
    ("billing_error", "Duplicate charge corrected"),
    ("downgrade", "Pro-rated credit after downgrade"),
    ("cancellation", "Pro-rated refund on early cancellation"),
    ("sla_credit", "Uptime credit per SLA section 4.2"),
]

# Near-duplicate pairs, injected verbatim so entity-resolution and the
# "ambiguous customer reference" clarification route have real data to hit.
DUPLICATE_NAME_PAIRS = [
    ("Acme Corp", "ACME Corporation"),
    ("Globex Industries", "Globex Industrial Group"),
    ("Initech LLC", "Initech Limited"),
    ("Umbrella Health", "Umbrella Healthcare"),
    ("Stark Logistics", "Stark Logistic Services"),
    ("Wayne Data", "Wayne Data Systems"),
    ("Soylent Foods", "Soylent Food Group"),
    ("Hooli Systems", "Hooli System Partners"),
]


@dataclass
class GeneratedData:
    """In-memory result of a generation run, ready for the loader."""

    customers: list[dict] = field(default_factory=list)
    contacts: list[dict] = field(default_factory=list)
    subscriptions: list[dict] = field(default_factory=list)
    subscription_changes: list[dict] = field(default_factory=list)
    usage: list[dict] = field(default_factory=list)
    invoices: list[dict] = field(default_factory=list)
    invoice_items: list[dict] = field(default_factory=list)
    payments: list[dict] = field(default_factory=list)
    refunds: list[dict] = field(default_factory=list)
    tickets: list[dict] = field(default_factory=list)
    ticket_events: list[dict] = field(default_factory=list)
    sla_breaches: list[dict] = field(default_factory=list)
    incidents: list[dict] = field(default_factory=list)
    incident_impact: list[dict] = field(default_factory=list)
    health: list[dict] = field(default_factory=list)

    def counts(self) -> dict[str, int]:
        return {
            name: len(getattr(self, name))
            for name in (
                "customers", "contacts", "subscriptions", "subscription_changes",
                "usage", "invoices", "invoice_items", "payments", "refunds",
                "tickets", "ticket_events", "sla_breaches", "incidents",
                "incident_impact", "health",
            )
        }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _season_multiplier(when: date) -> float:
    """Q4 uplift, Q1 dip. Makes revenue trends look like a real SaaS business."""
    return {1: 0.8, 2: 1.0, 3: 1.05, 4: 1.4}[(when.month - 1) // 3 + 1]


def _churn_multiplier(when: date) -> float:
    """Q2 2025 spike, traceable to the June 2025 SEV1 incident."""
    if when.year == 2025 and when.month in (4, 5, 6):
        return 2.5
    return 1.0


def _month_starts(start: date, end: date) -> list[date]:
    months, cursor = [], date(start.year, start.month, 1)
    while cursor <= end:
        months.append(cursor)
        cursor = date(cursor.year + (cursor.month == 12), (cursor.month % 12) + 1, 1)
    return months


def _add_months(when: date, count: int) -> date:
    total = when.month - 1 + count
    year, month = when.year + total // 12, total % 12 + 1
    day = min(when.day, [31, 29 if year % 4 == 0 else 28, 31, 30, 31, 30,
                         31, 31, 30, 31, 30, 31][month - 1])
    return date(year, month, day)


class SyntheticGenerator:
    """Builds the full dataset from a fixed seed."""

    def __init__(self, settings: Settings, volumes: Volumes, reference: dict) -> None:
        from faker import Faker

        self.settings = settings
        self.volumes = volumes
        self.reference = reference  # tenants / products / plans / sla_policies from the DB

        seed = settings.random_seed
        self.rng = random.Random(seed)
        self.faker = Faker("en_US")
        Faker.seed(seed)

        self.data = GeneratedData()

    # -- customers ---------------------------------------------------------
    def generate_customers(self) -> None:
        tenants = self.reference["tenants"]
        target = self.volumes.customers

        # Near-duplicate pairs first, so they always exist regardless of volume.
        forced_names: list[str] = []
        for left, right in DUPLICATE_NAME_PAIRS:
            forced_names.extend([left, right])

        for index in range(target):
            tenant = self.rng.choices(tenants, weights=[0.5, 0.3, 0.2])[0]

            if index < len(forced_names):
                display = forced_names[index]
                legal = f"{display} {self.rng.choice(['Inc.', 'Ltd.', 'GmbH', 'LLC'])}"
            else:
                display = self.faker.company()
                legal = f"{display} {self.rng.choice(['Inc.', 'Ltd.', 'GmbH', 'LLC', 'S.A.'])}"

            segment = self.rng.choices(
                ["SMB", "MidMarket", "Enterprise"], weights=[0.5, 0.33, 0.17]
            )[0]

            # Signups are spread across the window, weighted to later periods so
            # the customer base grows rather than appearing fully formed.
            span = (DATA_END - DATA_START).days - 60
            signup = DATA_START + timedelta(days=int(self.rng.betavariate(1.6, 1.0) * span))

            is_trial_only = self.rng.random() < 0.08

            record = {
                "tenant_id": tenant["tenant_id"],
                "customer_code": f"CUST-{index + 1:05d}",
                "legal_name": legal[:200],
                "display_name": display[:200],
                # ~12% missing industry: a real CRM always has gaps.
                "industry": None if self.rng.random() < 0.12 else self.rng.choice(INDUSTRIES),
                "segment": segment,
                "country_code": self._country_for(tenant),
                "region": tenant["region"],
                "employee_count": None if self.rng.random() < 0.15 else self._employees(segment),
                "billing_currency": tenant["default_currency"],
                "time_zone": tenant["time_zone"],
                "signup_date": signup,
                "churn_date": None,
                "status": "trial" if is_trial_only else "active",
                "is_reactivated": 0,
                "_is_trial_only": is_trial_only,
                "_index": index,
            }
            self.data.customers.append(record)

        self._generate_contacts()

    def _country_for(self, tenant: dict) -> str:
        pools = {
            "North America": ["US", "US", "US", "CA", "MX"],
            "EMEA": ["DE", "FR", "GB", "NL", "ES", "IT", "SE", "AE"],
            "APAC": ["SG", "AU", "JP", "IN", "NZ", "KR"],
        }
        return self.rng.choice(pools[tenant["region"]])

    def _employees(self, segment: str) -> int:
        ranges = {"SMB": (5, 200), "MidMarket": (200, 2000), "Enterprise": (2000, 60000)}
        low, high = ranges[segment]
        return self.rng.randint(low, high)

    def _generate_contacts(self) -> None:
        for customer in self.data.customers:
            for slot in range(self.rng.randint(1, 3)):
                name = self.faker.name()
                domain = (
                    customer["display_name"].lower()
                    .replace(" ", "").replace(",", "").replace(".", "")[:20]
                )
                self.data.contacts.append({
                    "_customer_index": customer["_index"],
                    "tenant_id": customer["tenant_id"],
                    "full_name": name,
                    "email": f"{name.split()[0].lower()}.{name.split()[-1].lower()}@{domain}.example",
                    # ~30% missing phone.
                    "phone": None if self.rng.random() < 0.30 else self.faker.numerify("+1-###-###-####"),
                    "role_title": self.rng.choice([
                        "VP Engineering", "Head of Data", "IT Director", "CTO",
                        "Operations Manager", "Procurement Lead", None,
                    ]),
                    "is_primary": 1 if slot == 0 else 0,
                    "is_synthetic": 1,
                })

    # -- subscriptions -----------------------------------------------------
    def generate_subscriptions(self) -> None:
        plans = self.reference["plans"]
        by_tier: dict[str, list[dict]] = {}
        for plan in plans:
            by_tier.setdefault(plan["tier"], []).append(plan)

        tier_for_segment = {
            "SMB": ["Starter", "Starter", "Professional"],
            "MidMarket": ["Professional", "Professional", "Enterprise"],
            "Enterprise": ["Enterprise", "Enterprise", "Professional"],
        }

        for customer in self.data.customers:
            count = 1 if customer["_is_trial_only"] else self.rng.choices([1, 2, 3], weights=[0.6, 0.3, 0.1])[0]

            for _ in range(count):
                tier = self.rng.choice(tier_for_segment[customer["segment"]])
                plan = self.rng.choice(by_tier[tier])

                start = customer["signup_date"] + timedelta(days=self.rng.randint(0, 30))
                if start > DATA_END:
                    start = DATA_END - timedelta(days=30)

                seats = max(1, int(plan["seats_included"] * self.rng.uniform(0.6, 1.8)))
                discount = self.rng.choice([0, 0, 0, 5, 10, 15, 20])
                mrr = round(
                    float(plan["list_price_monthly"]) * (seats / max(plan["seats_included"], 1))
                    * (1 - discount / 100), 4
                )
                mrr = max(mrr, 0)

                is_trial = 1 if customer["_is_trial_only"] else 0
                status, ended_on, reason = "active", None, None

                if not is_trial:
                    # Churn probability rises with the seasonal churn multiplier.
                    months_live = max(1, (DATA_END - start).days // 30)
                    base_monthly_churn = 0.012
                    for month_index in range(months_live):
                        when = _add_months(start, month_index)
                        if when > DATA_END:
                            break
                        if self.rng.random() < base_monthly_churn * _churn_multiplier(when):
                            ended_on = min(when, DATA_END)
                            status = "cancelled"
                            reason = self.rng.choice(CANCEL_REASONS)
                            break
                else:
                    status = "trial"
                    ended_on = min(start + timedelta(days=30), DATA_END)

                subscription = {
                    "_customer_index": customer["_index"],
                    "tenant_id": customer["tenant_id"],
                    "plan_id": plan["plan_id"],
                    "_plan": plan,
                    "started_on": start,
                    "ended_on": ended_on,
                    "status": status,
                    "seats": seats,
                    "mrr_amount": mrr,
                    "discount_pct": discount,
                    "currency_code": customer["billing_currency"],
                    "is_trial": is_trial,
                    "auto_renew": 1 if status == "active" else 0,
                    "cancellation_reason": reason,
                    "_index": len(self.data.subscriptions),
                }
                self.data.subscriptions.append(subscription)
                self._record_changes(customer, subscription, by_tier)

        self._apply_churn_to_customers()
        self._apply_reactivations()

    def _record_changes(self, customer: dict, sub: dict, by_tier: dict) -> None:
        """New / upgrade / downgrade / seat change / cancel events."""
        base = {
            "_customer_index": customer["_index"],
            "_subscription_index": sub["_index"],
            "tenant_id": customer["tenant_id"],
        }
        self.data.subscription_changes.append({
            **base, "change_type": "new", "changed_on": sub["started_on"],
            "from_plan_id": None, "to_plan_id": sub["plan_id"],
            "from_seats": None, "to_seats": sub["seats"],
            "from_mrr": None, "to_mrr": sub["mrr_amount"],
            "mrr_delta": sub["mrr_amount"], "reason": "New subscription",
        })

        if sub["is_trial"]:
            return

        # ~22% of subscriptions see a plan migration.
        if self.rng.random() < 0.22:
            end_bound = sub["ended_on"] or DATA_END
            if (end_bound - sub["started_on"]).days > 90:
                when = sub["started_on"] + timedelta(
                    days=self.rng.randint(60, max(61, (end_bound - sub["started_on"]).days - 10))
                )
                upgrade = self.rng.random() < 0.6
                factor = self.rng.uniform(1.2, 1.9) if upgrade else self.rng.uniform(0.5, 0.85)
                new_mrr = round(sub["mrr_amount"] * factor, 4)
                self.data.subscription_changes.append({
                    **base,
                    "change_type": "upgrade" if upgrade else "downgrade",
                    "changed_on": when,
                    "from_plan_id": sub["plan_id"], "to_plan_id": sub["plan_id"],
                    "from_seats": sub["seats"], "to_seats": sub["seats"],
                    "from_mrr": sub["mrr_amount"], "to_mrr": new_mrr,
                    "mrr_delta": round(new_mrr - sub["mrr_amount"], 4),
                    "reason": "Plan migration" if upgrade else "Cost reduction",
                })
                sub["mrr_amount"] = new_mrr

        # Seat changes, which can be positive (expansion) or negative (contraction).
        if self.rng.random() < 0.18:
            end_bound = sub["ended_on"] or DATA_END
            if (end_bound - sub["started_on"]).days > 120:
                when = sub["started_on"] + timedelta(
                    days=self.rng.randint(90, max(91, (end_bound - sub["started_on"]).days - 5))
                )
                delta_seats = self.rng.choice([-5, -3, -2, 2, 3, 5, 10])
                new_seats = max(1, sub["seats"] + delta_seats)
                per_seat = sub["mrr_amount"] / max(sub["seats"], 1)
                new_mrr = round(per_seat * new_seats, 4)
                self.data.subscription_changes.append({
                    **base, "change_type": "seat_change", "changed_on": when,
                    "from_plan_id": sub["plan_id"], "to_plan_id": sub["plan_id"],
                    "from_seats": sub["seats"], "to_seats": new_seats,
                    "from_mrr": sub["mrr_amount"], "to_mrr": new_mrr,
                    "mrr_delta": round(new_mrr - sub["mrr_amount"], 4),
                    "reason": "Seat adjustment",
                })
                sub["seats"], sub["mrr_amount"] = new_seats, new_mrr

        if sub["ended_on"] is not None and sub["status"] == "cancelled":
            self.data.subscription_changes.append({
                **base, "change_type": "cancel", "changed_on": sub["ended_on"],
                "from_plan_id": sub["plan_id"], "to_plan_id": None,
                "from_seats": sub["seats"], "to_seats": 0,
                "from_mrr": sub["mrr_amount"], "to_mrr": 0,
                "mrr_delta": -sub["mrr_amount"],
                "reason": sub["cancellation_reason"],
            })

    def _apply_churn_to_customers(self) -> None:
        """A customer churns when every non-trial subscription has ended."""
        by_customer: dict[int, list[dict]] = {}
        for sub in self.data.subscriptions:
            by_customer.setdefault(sub["_customer_index"], []).append(sub)

        for customer in self.data.customers:
            subs = [s for s in by_customer.get(customer["_index"], []) if not s["is_trial"]]
            if not subs:
                if customer["_is_trial_only"]:
                    customer["status"] = "trial"
                continue
            if all(s["ended_on"] is not None for s in subs):
                customer["churn_date"] = max(s["ended_on"] for s in subs)
                customer["status"] = "churned"
            else:
                customer["status"] = "active"
                customer["churn_date"] = None

    def _apply_reactivations(self) -> None:
        """~4% of churned customers come back. Their churn_date is cleared."""
        churned = [c for c in self.data.customers if c["status"] == "churned"]
        for customer in churned:
            if self.rng.random() >= 0.04:
                continue
            restart = customer["churn_date"] + timedelta(days=self.rng.randint(45, 240))
            if restart >= DATA_END:
                continue

            plan = self.rng.choice(self.reference["plans"])
            seats = max(1, int(plan["seats_included"] * self.rng.uniform(0.6, 1.4)))
            mrr = round(float(plan["list_price_monthly"]) * (seats / max(plan["seats_included"], 1)), 4)

            sub = {
                "_customer_index": customer["_index"],
                "tenant_id": customer["tenant_id"],
                "plan_id": plan["plan_id"], "_plan": plan,
                "started_on": restart, "ended_on": None, "status": "active",
                "seats": seats, "mrr_amount": mrr, "discount_pct": 0,
                "currency_code": customer["billing_currency"], "is_trial": 0,
                "auto_renew": 1, "cancellation_reason": None,
                "_index": len(self.data.subscriptions),
            }
            self.data.subscriptions.append(sub)
            self.data.subscription_changes.append({
                "_customer_index": customer["_index"],
                "_subscription_index": sub["_index"],
                "tenant_id": customer["tenant_id"],
                "change_type": "reactivate", "changed_on": restart,
                "from_plan_id": None, "to_plan_id": plan["plan_id"],
                "from_seats": None, "to_seats": seats,
                "from_mrr": 0, "to_mrr": mrr, "mrr_delta": mrr,
                "reason": "Customer returned",
            })
            customer["status"] = "active"
            customer["churn_date"] = None
            customer["is_reactivated"] = 1
